### ISSUE TITLE
Float support

### ISSUE THREAD

**Issue by luke-j** [alirizwan/sequelize-graphql-schema#14]
Hi - thanks for the package, very helpful!

Is there a particular reason why the graphql scalar `Float` is not supported? Currently `DECIMAL`s, `DOUBLE`s etc. are treated as strings.

**Comment by alirizwan** [comment]
unfortunately this is a bug in underlying library graphql-sequelize which convert these to string, i have been thinking about raising a PR on this, about custom types, I am already working on releasing support for all available types this week.
