### ISSUE TITLE
Cannot read property 'paranoid' of undefined

### ISSUE THREAD

**Issue by erickml** [alirizwan/sequelize-graphql-schema#16]
When i try to generate the schema using a sequelize model, i got this error. What config is required to dont get this issue anymore.
<img width="1354" alt="screen shot 2019-02-21 at 12 23 44 pm" src="https://user-images.githubusercontent.com/26806818/53188769-10a37f00-35d4-11e9-9267-165bb8bd6b35.png">

**Comment by alirizwan** [comment]
can you please send me these files so while reproducing i don't have to write all of it? Meanwhile I will try to recreate using a similar model to the one you have up there. Fortunately this feature is being used in production so there are less chances that its breaking it but still I think it's a bug that if paranoid is not present it shouldn't throw this error.

For now you can use this option in your model to make it work:
```
.....
{
tableName: 'category',
paranoid: false
}
```

**Comment by erickml** [comment]
My model is: 
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('category', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING(55),
      allowNull: false
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false
    },
    created_by: {
      type: DataTypes.STRING(45),
      allowNull: false
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false
    },
    updated_by: {
      type: DataTypes.STRING(45),
      allowNull: false
    }
  }, {
    tableName: 'category',
    timestamps: false,
    underscored: false,
    paranoid: false
  });
};
The model already has the attribute paranoid.

**Comment by erickml** [comment]
Databaje.js

import Sequelize from 'sequelize'
import fs from 'fs'
import path from 'path'

class Database {

  constructor(props) {
    this.db_host = props.DB_HOST
    this.db_name = props.DB_NAME
    this.db_user = props.DB_USER
    this.db_password = props.DB_PASSWORD
    this.db_dialect = props.DB_DIALECT
    this.sequelize = null
  }

  getConnection() {
    this.sequelize = new Sequelize(this.db_name, this.db_user, this.db_password, {
      host: this.db_host,
      dialect: this.db_dialect,
    });
    this.setModels()
    return this.sequelize
  }

  setModels() {
    fs.readdirSync(path.join(__dirname, 'models')).forEach(file => {
      if (file.search('.js') >= 0) {
        this.sequelize.import(path.join(__dirname, 'models') + '/' + file)
      }
    })
  }

}

export default Database
