### ISSUE TITLE
useCLS error

### ISSUE THREAD

**Issue by michaelyiu** [alirizwan/sequelize-graphql-schema#18]
Wondering what the model files are supposed to look like. I've already defined models and resolvers and also have built my own schemas as well, but wanted to see if this gave more functionality. However, I'm bumping into an issue where it seems like it doesn't like the models I've built. I do have the dependencies sequelize and graphql installed.

**Comment by alirizwan** [comment]
Can you please post full error here or your code to see the error? You can check tests folder for an example how this library works.

**Comment by michaelyiu** [comment]
src/index.js
```
...imports

var { GraphQLSchema } = require('graphql');
const { generateSchema } = require('sequelize-graphql-schema')()
const schema = new GraphQLSchema(generateSchema(models))

const server = new ApolloServer({
  typeDefs: schema,
  resolvers,
    return {
      ...error,
      message,
    };
  },
  context: async ({ req, res }) => {
    return {
      models,
      me,
      secret: "notSoSecret",
    }
  },
  path: "/graphql"
});

server.applyMiddleware({ app });
app.get("/playground", graphiql({ endpoint: "/graphql" }));

const handler = serverless(app);
export { handler };
```

One of many model files

```
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Role = sequelize.define('role', {
    id: {
      type: DataTypes.INTEGER.UNSIGNED,
      autoIncrement: true,
      primaryKey: true
    },
    slug: {
      allowNull: false,
      type: DataTypes.STRING,
    },
    description: {
      allowNull: false,
      type: DataTypes.STRING,
    },
    created_at: {
      type: 'TIMESTAMP',
    },
    updated_at: {
      type: 'TIMESTAMP',
    }
  }, {
      underscored: true,
    });
  Role.associate = function (models) {
    // associations can be defined here
  };
  return Role;
};
```

> {"errorMessage":"Error while loading playground","errorType":"TypeError","stackTrace":["TypeError: Cannot read property 'useCLS' of undefined","at generateSchema (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\sequelize-graphql-schema\\dist\\sequelize-graphql-schema.js:869:20)","at Module../src/index.js (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:322:34)","at __webpack_require__ (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:21:30)","at C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:85:18","at Object.<anonymous> (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:88:10)","at Module._compile (internal/modules/cjs/loader.js:688:30)","at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)","at Module.load (internal/modules/cjs/loader.js:598:32)","at tryModuleLoad (internal/modules/cjs/loader.js:537:12)","at Function.Module._load (internal/modules/cjs/loader.js:529:3)","at Module.require (internal/modules/cjs/loader.js:636:17)","at require (internal/modules/cjs/helpers.js:20:18)","at Object.createHandler (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\serverless-offline\\src\\functionHelper.js:104:21)","at handler (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\serverless-offline\\src\\index.js:590:40)","at Object.internals.handler (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\handler.js:96:36)","at request._protect.run (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\handler.js:30:23)","at module.exports.internals.Protect.internals.Protect.run (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\protect.js:64:5)","at exports.execute (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\handler.js:24:22)","at each (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at done (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:28:25)","at module.exports.internals.Auth.internals.Auth._authenticate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\auth.js:210:16)","at internals.Auth.authenticate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\auth.js:202:17)","at each (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at done (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:28:25)","at request.connection.states.parse (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\route.js:379:20)","at Items.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\statehood\\lib\\index.js:244:16)","at done (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:31:25)","at Items.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\statehood\\lib\\index.js:184:20)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at Object.exports.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:39:9)","at exports.Definitions.internals.Definitions.internals.Definitions.parse (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\statehood\\lib\\index.js:158:11)","at internals.state (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\route.js:360:31)","at each (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at Object.exports.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:39:9)","at internals.Request._lifecycle (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:387:11)","at internals.Request._execute (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:302:21)","at Domain.request._protect.enter (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\connection.js:261:25)","at Domain.run (domain.js:343:14)","at module.exports.internals.Protect.internals.Protect.enter (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\protect.js:80:17)","at Server.<anonymous> (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\connection.js:259:30)","at Server.emit (events.js:182:13)","at Server.EventEmitter.emit (domain.js:442:20)","at parserOnIncoming (_http_server.js:672:12)"],"offlineInfo":"If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"}

**Comment by alirizwan** [comment]
it seems like the models you are passing doesn't have an object Sequelize along with it as in https://github.com/alirizwan/sequelize-graphql-schema/blob/ab613a02609226aeae97bf71377d805bbb99924c/tests/models/index.js#L40

I believe in next update I can make changes so we can have more ways to pass Sequelize objects instead of the way it is now.

**Comment by michaelyiu** [comment]
I failed to mention that I do have an index file as follows that I think may make a difference:

```
import Sequelize from "sequelize";
import config from "./../config/config";
const sequelize = new Sequelize(config.db.database, config.db.username, config.db.password, config.db.options);

const roleModel = require("./Role.js");

const models = {
  Role: sequelize.import("role", roleModel),
}

Object.keys(models).forEach(key => {
	if ("associate" in models[key]) {
		models[key].associate(models);
	}
});

export { sequelize };
export default models;
```

**Comment by alirizwan** [comment]
you are not exporting `Sequelize` but only `sequelize`. You need to export all three `sequelize` `Sequelize` and `models`;

**Comment by michaelyiu** [comment]
Okay so I made the following changes in which I believe reflects what you've mentioned, and I'm getting a new error:

models/index.js
```
import Sequelize from "sequelize";
import config from "./../config/config";
const sequelize = new Sequelize(config.db.database, config.db.username, config.db.password, config.db.options);

const roleModel = require("./Role.js");

const models = {
  Role: sequelize.import("role", roleModel),
}

Object.keys(models).forEach(key => {
	if ("associate" in models[key]) {
		models[key].associate(models);
	}
});

models.sequelize = sequelize;
models.Sequelize = Sequelize;
export default models;
```

Error:
{"errorMessage":"Error while loading playground","errorType":"TypeError","stackTrace":["TypeError: Cannot read property 'options' of undefined","at C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\sequelize-graphql-schema\\dist\\sequelize-graphql-schema.js:621:49","at Array.reduce (<anonymous>)","at generateQueryRootType (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\sequelize-graphql-schema\\dist\\sequelize-graphql-schema.js:610:43)","at generateSchema (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\sequelize-graphql-schema\\dist\\sequelize-graphql-schema.js:925:14)","at Module../src/index.js (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:322:34)","at __webpack_require__ (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:21:30)","at C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:85:18","at Object.<anonymous> (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\.webpack\\service\\src\\index.js:88:10)","at Module._compile (internal/modules/cjs/loader.js:688:30)","at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)","at Module.load (internal/modules/cjs/loader.js:598:32)","at tryModuleLoad (internal/modules/cjs/loader.js:537:12)","at Function.Module._load (internal/modules/cjs/loader.js:529:3)","at Module.require (internal/modules/cjs/loader.js:636:17)","at require (internal/modules/cjs/helpers.js:20:18)","at Object.createHandler (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\serverless-offline\\src\\functionHelper.js:104:21)","at handler (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\serverless-offline\\src\\index.js:590:40)","at Object.internals.handler (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\handler.js:96:36)","at request._protect.run (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\handler.js:30:23)","at module.exports.internals.Protect.internals.Protect.run (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\protect.js:64:5)","at exports.execute (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\handler.js:24:22)","at each (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at done (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:28:25)","at module.exports.internals.Auth.internals.Auth._authenticate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\auth.js:210:16)","at internals.Auth.authenticate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\auth.js:202:17)","at each (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at done (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:28:25)","at request.connection.states.parse (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\route.js:379:20)","at Items.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\statehood\\lib\\index.js:244:16)","at done (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:31:25)","at Items.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\statehood\\lib\\index.js:184:20)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at Object.exports.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:39:9)","at exports.Definitions.internals.Definitions.internals.Definitions.parse (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\statehood\\lib\\index.js:158:11)","at internals.state (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\route.js:360:31)","at each (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:384:16)","at iterate (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:36:13)","at Object.exports.serial (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\items\\lib\\index.js:39:9)","at internals.Request._lifecycle (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:387:11)","at internals.Request._execute (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\request.js:302:21)","at Domain.request._protect.enter (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\connection.js:261:25)","at Domain.run (domain.js:343:14)","at module.exports.internals.Protect.internals.Protect.enter (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\protect.js:80:17)","at Server.<anonymous> (C:\\Users\\Mike\\Desktop\\test\\apollo-server-api\\node_modules\\hapi\\lib\\connection.js:259:30)","at Server.emit (events.js:182:13)","at Server.EventEmitter.emit (domain.js:442:20)","at parserOnIncoming (_http_server.js:672:12)"],"offlineInfo":"If you believe this is an issue with the plugin please submit it, thanks. https://github.com/dherault/serverless-offline/issues"}

So I tried putting some options in I had required the package and the result would be the same, tried removing it altogether and just having: 
`const { generateSchema } = require('sequelize-graphql-schema')`
would say that generateSchema is not defined.

**Comment by alirizwan** [comment]
I tried to re-produce it and found a couple of issues. When you import your model, import it as model name instead of giving it a name of your own unless the name matches with the model name for example, model name is `role` but your key in models object is `Role`. It's better to do it like this:
`const models = {};
const roleModel = sequelize['import']('./Role.js');
models[roleModel.name] = roleModel;
`
For model importing if you could use the logic we have in `tests/models/index.js` that's pretty generic and automatically imports all of available models.

Second 
`created_at: {
      type: 'TIMESTAMP',
    },
    updated_at: {
      type: 'TIMESTAMP',
    }` you don't need these two columns, if you want to use `DataTypes.DATE`

**Comment by alirizwan** [comment]
https://github.com/alirizwan/sequelize-graphql-schema/issues/19
closing this issue.
