### ISSUE TITLE
Update graphql dependency to 14.1.1

### ISSUE THREAD

**Issue by emanuelet** [alirizwan/sequelize-graphql-schema#3]
I think it would be good to upgrade to the last version of graphql so that people can use all the latest features. Moreover, I'm forced to keep the version back on my package.json as well to avoid breaking the library

**Comment by alirizwan** [comment]
indeed and would do that. But i think if you want to use a newer version you can use 
```
"resolutions": {
    "graphql": "^0.13.2"
  },
```
in your project's package.json and it should use specified version of graphql.

**Comment by alirizwan** [comment]
this is resolved in `0.1.54`. graphql is no longer a peer-dependency as well.
