### ISSUE TITLE
Example of how to use "join" option?

### ISSUE THREAD

**Issue by charlie-s** [alirizwan/sequelize-graphql-schema#38]
We're on 1.0.0-beta.11. I'm trying to require inner joins on some queries to limit the result set. It looks like  https://github.com/almost-full-stack/sequelize-graphql-schema/pull/34 covers it. Is that the case? If so, how can I use an inner join in my query? For example:

```
{
  Design (
    where: {
      customerId: 2635
    }
  ) {
    id
    name
    DesignLocations {
      location
    }
  }
}
```

we'd like to limit the result set with an inner join. Actually, we have a 3rd level of relation that we'd like to require as well if that doesn't overcomplicate things.

**Comment by alirizwan** [comment]
you might have noticed that we have refactored heavily and still bringing some of the older functionality to new version. PR#34 solves that, I haven't started working on that yet but i will expedite that. However we have a plan for n level relations the only problem I was facing was dataloader. I had to make altogether new functionality to support this. But this is something which is WIP.

**Comment by charlie-s** [comment]
Got it, sounds good. Yes I noticed syntax and such has changed, but things look like they're headed in an even better direction. I'll punch up a custom query for now, it's simple enough. Thanks as always for the fast response.

**Comment by alirizwan** [comment]
`1.0.0-beta.12` has join feature.

You won't get it by default but you have to switch it on using model configurations.
When you turn it on, for example https://github.com/almost-full-stack/sequelize-graphql-schema/pull/36/files#diff-191c99adf95ea6fafde0338a21ed43beR35

all the associations of that model will be generated with `join` argument which then can be used as following and you can mix your associations as well with or without join:

```{
  Product{
    id
    name
    Attributes(join:LEFT, where:{id:1}){
      id
      name
    }
    Images(where:{id:1}){
      id
      url
    }
  }
}
```

This feature might need more improvement, looking forward to your feedback on this.

**Comment by charlie-s** [comment]
Hey Ali,

Hope you’re doing well, especially with everything going on right now. How’s the day-to-day where you are?

I wanted to see if you’re available to work on our codebase a bit. We’d like to update to the latest version of GraphCraft (nice name!) and ensure we’re following best practices. I know there are syntax changes and such. Let me know your thoughts. Thanks for everything on the module again!

- Charlie

On Jan 11, 2020, at 4:49 PM, Ali Rizwan <notifications@github.com> wrote:

﻿

1.0.0-beta.12 has join feature.

You won't get it by default but you have to switch it on using model configurations.
When you turn it on, for example https://github.com/almost-full-stack/sequelize-graphql-schema/pull/36/files#diff-191c99adf95ea6fafde0338a21ed43beR35

all the associations of that model will be generated with join argument which then can be used like:

  Product{
    id
    name
    Attributes(join:LEFT, where:{id:1}){
      id
      name
    }
    Images(where:{id:1}){
      id
      url
    }
  }
}


This feature might need more improvement, looking forward to your feedback on this.
