### ISSUE TITLE
1.0.0-beta.17 questions

### ISSUE THREAD

**Issue by RenatoFranze** [alirizwan/sequelize-graphql-schema#41]
Hi guys, 

I was testing version 1.0.0-beta.17 to see the new funcionalitys and two points came up:

- Querys and Mutations names pattern changed. In the stable version a Sequelize model "ws_export" becames "wsExportGet" and now is "WsExport". Is this new pattern that will be adopted? Is there any way to make an alias and rewrite to the previous pattern? Cause I have a few projects calling my graphql endpoint and rewrite them to use the new pattern will be caotic. 

- The resetCache function stop working. Is this normal?

Thanks!

**Comment by alirizwan** [comment]
Hi, the naming previous to beta was more of an internal naming and was not really flexible one. In newer version naming is more towards best practices and is flexible allowing you to choose your own naming scheme. Read about it here https://github.com/almost-full-stack/sequelize-graphql-schema/blob/feature/refactor/README.md it's the first one in Library Options section.
If you simply want to go back to your previous way of naming you don't have to define alias but only change naming options:
```
naming: {
  pascalCase: false,
  queries: '{name}Get`,
  type: {update: 'Edit'}
}

```
and it should generate names like `0.x` version.

About resetCache, it should work fine and if it's not, it is not normal. I will take a look at it and come back to you if there's a problem.

**Comment by RenatoFranze** [comment]
Thanks @alirizwan , the naming property worked like a charm!

I will be waiting about the resetCache.

**Comment by RenatoFranze** [comment]
Hi @alirizwan , 

Another question came up using the beta.17 version. 

Previously, using the 0.1.71 version, this bulk edit worked:

```code
mutation{
  productsEditBulk(products: [
    {
    sku: "0245552006000011",
    gross_weight: 1.00,
    net_weight: 1.00,
    uom: "VOL",
    barcode: "0245552006000011",
    description: "Volume 00001/00001"
  },
  {
    sku: "0245552006000012",
    gross_weight: 1,
    net_weight: 1,
    uom: "VOL",
    barcode: "0245552006000012",
    description: "Volume 00001/00001"
  }
  ]){
    sku
  }
}
```
And in the beta, this same bulk throws an error:
`"Invalid value {\n  sku: '0245552006000011',\n  gross_weight: 1,\n  net_weight: 1,\n  uom: 'VOL',\n  barcode: '0245552006000011',\n  description: 'Volume 00001/00001'\n}"`

```code
mutation{
  productsEditBulk(sku: [
    {
    sku: "0245552006000011",
    gross_weight: 1.00,
    net_weight: 1.00,
    uom: "VOL",
    barcode: "0245552006000011",
    description: "Volume 00001/00001"
  },
  {
    sku: "0245552006000012",
    gross_weight: 1,
    net_weight: 1,
    uom: "VOL",
    barcode: "0245552006000012",
    description: "Volume 00001/00001"
  }
  ])
}
```

Is there anything that I need to change in the model to get this working when using the beta version?

Thanks.

**Comment by alirizwan** [comment]
Hi, sorry I have been away past few days. Can you share your model?

**Comment by RenatoFranze** [comment]
Sure,

```code
module.exports = function(sequelize, DataTypes) {
	const Product = sequelize.define('products', 
		{
			sku: {
				type: DataTypes.STRING(45),
				allowNull: false,
				primaryKey: true
			},
			gross_weight: {
				type: DataTypes.FLOAT,
				allowNull: true
			},
			net_weight: {
				type: DataTypes.FLOAT,
				allowNull: true
			},
			uom: {
				type: DataTypes.STRING(5),
				allowNull: false
			},
			barcode: {
				type: DataTypes.STRING(45),
				allowNull: false
			},
			description: {
				type: DataTypes.STRING(45),
				allowNull: true
			}
		}, 
		{
			tableName: 'products',
			timestamps: false,
			createdAt: false,
			updatedAt: false,
			deletedAt: false
		}
	);

	Product.associate = (models) => {
		Product.hasMany(models.items, {
			foreignKey: 'product_sku'
		});
	}

	Product.graphql = {
		'bulk': ['create','update'],
	}

	return Product;
};
```

**Comment by RenatoFranze** [comment]
Hi, 

Any news?

**Comment by alirizwan** [comment]
this bugs are resolved, please use https://www.npmjs.com/package/graphcraft/v/1.0.0-beta.24

**Comment by alirizwan** [comment]
the package is renamed to graphcraft and sequelize-graphql-schema would be deprecated as soon as 1.0 is launched.
