### ISSUE TITLE
Upload functionality in 1.0.0-beta.17

### ISSUE THREAD

**Issue by ronakkoradiya** [alirizwan/sequelize-graphql-schema#42]
How can I implement file upload functionality with custom type?

**Comment by alirizwan** [comment]
You cannot upload files with graphql like you can do with REST APIs, you have to either convert your files to base64 on the frontend and then use those to upload files or have to go for REST endpoint for file uploads. If you are uploading files to S3 then generate signedurl via graphql and then use that signed url on the frontend to upload files.

**Comment by ronakkoradiya** [comment]
I am trying to use "graphql-upload" for creating custom upload mutation but for that, I have to create custom type "Upload". How can I create a custom type?

**Comment by alirizwan** [comment]
here you can find an example: https://github.com/almost-full-stack/graphcraft/blob/feature/refactor/tests/sequelize-graphql-schema.spec.js

look at types

**Comment by alirizwan** [comment]
if you want to create a custom type within a model, you can also do same in there by using type property.

**Comment by alirizwan** [comment]
Resolved.
