### ISSUE TITLE
inquiry: Possibility of selected sql fields

### ISSUE THREAD

**Issue by donecarlo** [alirizwan/sequelize-graphql-schema#43]
I'm currently exploring graphql and stumbled upon this project, and it's a great tool for my current project. I noticed though that by default, the execution of the `select` command fetches all columns. Would it be possible to have a feature to only select fields that were included in the original graphql query? Thanks!

**Comment by alirizwan** [comment]
It is possible to exclude columns for graphql (select would fetch all and I can think of a way to have this possibility as well) but until that's not available you can use exclude option.
https://github.com/almost-full-stack/graphcraft/blob/feature/refactor/src/index.js#L105

you can exclude via Model.graphql.attributes.exclude = ['id', 'name'] and so on and these columns won't be available in any of the type generated by package.

**Comment by jor3l** [comment]
Can we just pass the query fields to the attributes array so only those are returned and queried against the db https://sequelize.org/master/manual/model-querying-basics.html#specifying-attributes-for-select-queries
