### ISSUE TITLE
how to get query total count

### ISSUE THREAD

**Issue by morix-gao** [alirizwan/sequelize-graphql-schema#44]
for pagination, how do I get the total number of query results？

**Comment by alirizwan** [comment]
you can use the count query for it. Which version are you using?

**Comment by morix-gao** [comment]
> you can use the count query for it. Which version are you using?

Thank u for reply!   How to use count query in graphql client?  any examples api string of that？
"sequelize-graphql-schema": "^0.1.71"

**Comment by alirizwan** [comment]
I will recommend to upgrade to [graphcraft](https://www.npmjs.com/package/graphcraft/v/1.0.0-beta.39) it's more stable and has more features. You would see count queries in there as well for you.

**Comment by jasp402** [comment]
I have the same problem and if I am using **graphcraft 1.0.0-beta.21.**
It would be possible to show an example

**Comment by alirizwan** [comment]
you can see metadata queries, let's suppose you have a model `Product` then you would see a query `ProductCount`

```
ProductCount(where: {})
```
You can pass in your where clause and it should return the number of items.
