### ISSUE TITLE
How can I deny a request with authorizer()?

### ISSUE THREAD

**Issue by jasp402** [alirizwan/sequelize-graphql-schema#46]
I am trying to follow this example, but I want to deny requests. i thought i could place
` return Promise.resolve(false);`
and that the petition would be denied, however it is still executed.

```
const options = {
  exclude: ["payments"],
  authorizer: function authorizer(source, args, context, info) {
    const { fieldName } = info; // resource name
 
    return Promise.resolve();
  }
};
 
const { generateSchema } = require("graphcraft")(options);
```

Any idea how a petition can be denied?
Thank you!

**Comment by alirizwan** [comment]
When you want to deny, use `return Promise.reject()`

**Comment by jasp402** [comment]
I am extremely grateful to your library and your prompt response. I have been using it for a while now but we have decided to expand our project and are exploring the full potential of your tool.

I have noticed that I can have a better control of the error using a handled exception.

if you use the **`return Promise.reject();`** the message is as follows.
![image](https://user-images.githubusercontent.com/8978470/110956996-36199780-8319-11eb-8227-df09e18d76e6.png)

but if I use **`throw new Error('ACCESS DENIED');`**
![image](https://user-images.githubusercontent.com/8978470/110957103-4f224880-8319-11eb-99ef-2ddad56589a1.png)

I feel like I have less control over messages. But I would love to know your opinion and if it is a good practice or to refuse otherwise.

Thank you!

**Comment by alirizwan** [comment]
Hi, I forgot to reply :) You reject by throwing an error indeed. If you want to control errors, maybe we can have a feature to handle all errors. The way error is happening above is correct way to handle errors but I would love to know your proposal.
