### ISSUE TITLE
Exclude column from mutations

### ISSUE THREAD

**Issue by lewismclennan** [alirizwan/sequelize-graphql-schema#47]
Wondering if there is a way/ any thoughts on allow exclusions for specific columns on mutations.

I've tied my model to a view for ease of accessing key information from other tables and would still like to be able
for the mutation to update the base table, but excluding specific columns in the the update.

For example

```
      jobId: {
        autoIncrement: true,
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
      },
      guid: {
        type: DataTypes.UUID,
        allowNull: false,
        defaultValue: sequelize.fn('newid'),
      },
      buildingName: {
        type: DataTypes.STRING(50),
        allowNull: true,
     },
     description: {
        type: DataTypes.STRING(4000),
        allowNull: false,
      },
```

In the above model buildingName doesn't exist on the source table but does exist in the view the model is referencing.
When I'm allowing the user to mutate the model, it would be great if I could note that the buildingName is excluded from mutations and therefore won't be included in any auto-generated update statement.

so instead of it generating

```
insert into dbo.tJobs
(guid, buildingName, description)
VALUES( @1, @2, @3)
```

it would run 

```
insert into dbo.tJobs
(guid, description)
VALUES( @1,  @3)
```

as building name has been excluded from mutations.

Which would prevent the error I'm receiving on create mutations

"message": "The column reference \"inserted.discipline\" is not allowed because it refers to a base table that is not being modified in this statement."

Let me know your thoughts, or even if this is possible without creating a whole new custom mutation?

Thanks

**Comment by alirizwan** [comment]
This issue is more related to sequelize rather than this package. What I would suggest is to make two models, one for the view and one for the table. Set `readonly` option (`model.graphql.readonly=true`) to true, this will only generate a query for this. For the other model, `excludeQueries = ['fetch']` this way you can achieve what you are trying to do.
