### ISSUE TITLE
attributes: exclude is never used

### ISSUE THREAD

**Issue by Yehonal** [alirizwan/sequelize-graphql-schema#5]
attributes -> exclude option from README is declared but never used, so the feature is not implemented

i'm going to fix it, PR soon

**Comment by alirizwan** [comment]
it is being used, if you don't want to create queries/mutations for a sequelize model, you can pass the name in there and it won't generate operations for it.

**Comment by Yehonal** [comment]
i'm talking about attribute exclution not model exclusion

**Comment by alirizwan** [comment]
probably it's not being implemented.

**Comment by Yehonal** [comment]
it's pretty easy to implement since it's a feature of graphql-sequelize library that you're using internally

PR soon ;)

**Comment by Yehonal** [comment]
i've sent you the PR to fix it, could you merge please?

**Comment by alirizwan** [comment]
i will check the pr over the weekend and also setup CI.
