### ISSUE TITLE
custom mutations with multiple arguments?

### ISSUE THREAD

**Issue by jor3l** [alirizwan/sequelize-graphql-schema#55]
I tried many things but can't figure out how to make it work, I need some custom mutations that take multiple arguments and so far I understand I pass input, output and resolver but input won't work if I pass an array or anything really other than a plain string

**Comment by alirizwan** [comment]
Hi, can you share your code or configuration? I’d be happy to help you once I have that.

Sent from my iPhone

On Sep 4, 2021, at 12:54 AM, Jose Vera ***@***.***> wrote:

﻿

I tried many things but can't figure out how to make it work, I need some custom mutations that take multiple arguments and so far I understand I pass input, output and resolver but input won't work if I pass an array or anything really other than a plain string

**Comment by jor3l** [comment]
Nevermind, kinda figure out I had to define custom types to then use them as my input / output.
