### ISSUE TITLE
How to keep associations in pascalCase?

### ISSUE THREAD

**Issue by jor3l** [alirizwan/sequelize-graphql-schema#56]
I have many associations that instead of having the same naming as my classes type definitions, get a underscored case (just like the file name) so I end up with Products and products or SomethingElse and something_else (when associated).

Is there a way to keep everything with pascalCase?. Thanks!

**Comment by jor3l** [comment]
Fixed by naming each class model with a static name method, also updating the exports naming

**Comment by alirizwan** [comment]
There's a naming option in the package, you can always configure that to change your naming convention.
