### ISSUE TITLE
Bulk Update

### ISSUE THREAD

**Issue by lewismclennan** [alirizwan/sequelize-graphql-schema#61]
Just a quick question, I've found the ability to allow for bulk mutations to be exposed.

I've exposed both Create and Update.

However I've tried the Bulk Update and it seems to be trying to run a delete on the table rather than an update?

Many thanks,

Lewis

**Comment by lewismclennan** [comment]
Worked it out

**Comment by alirizwan** [comment]
Hi Lewis, it depends upon the relation. The delete happens can happen if you are running bulk update on a through model. If that's the case then it also depends what is the mode you are using. I know it's a bit confusing and I am trying to make it simple.  In the meantime I would like to see what you are trying to do, such as relation between models and your mutation.

**Comment by lewismclennan** [comment]
Thanks for your reply @alirizwan, do you have a contact address I can reach you at? as I'd rather not share some of the models publicly and I'm sure it would be easier to go over the issue that way.

**Comment by alirizwan** [comment]
***@***.***
Let’s discuss here

Sent from my iPhone

On Dec 10, 2021, at 10:07 AM, Lewis McLennan ***@***.***> wrote:

﻿

Thanks for your reply @alirizwan<https://github.com/alirizwan>, do you have a contact address I can reach you at? as I'd rather not share some of the models publicly and I'm sure it would be easier to go over the issue that way.

**Comment by lewismclennan** [comment]
That's a shame it seems to *** out your email address.

Can only see ***@***.***

**Comment by alirizwan** [comment]
ali.aruz at outlook dot com

Sent from my iPhone

On Dec 10, 2021, at 10:52 AM, Lewis McLennan ***@***.***> wrote:

﻿

That's a shame it seems to *** out your email address.

Can only see @.***
