### ISSUE TITLE
n:m queries are not correctly handled

### ISSUE THREAD

**Issue by Yehonal** [alirizwan/sequelize-graphql-schema#7]
Currently you can query a model associated with another with n:m, but if you need some field that are directly added in "through" model you are not able to retrieve them in any way.

for example if we have model Recipe associated with Ingredients via "RecipeIngredients" relational model that contains the quantity for each Recipe, you cannot access to the quantity field via a query.

It's a critical issue

**Comment by alirizwan** [comment]
you are right. It indeed is the case. I will see how we can fix it. It seems like an issue coming from graphql-sequelize.

**Comment by Yehonal** [comment]
Here you can find the issue asked on graphql-sequelize:

https://github.com/mickhansen/graphql-sequelize/issues/386

**Comment by alirizwan** [comment]
I have an idea how to fix it, there are two options, one to include through model's attributes in both n:m models and whenever someone queries we modify sequelize query output accordingly.

**Comment by alirizwan** [comment]
But it's a good catch, I didn't run into such situation so far but i guess i will think about and let you know as well.

**Comment by Yehonal** [comment]
This is how it's handled by graphql-sequelize-crud:
i've 3 tables for n:m association (recipe 1->n recipeIngredients n<-1 ingredients) where recipeIngredients table has quantities attribute inside
and this is the graphql query:
```
{
  recipes { // query to retrieve recipe from table (recipes)
    name   // recipe name
    Ingredients{ // query to retrieve ingredient relation
      edges {
        quantities // this is the field of relational table (recipeIngredients)
        node {  // the node is the true ingredient table (ingredients)
          name  // name of the ingredient 
        }
      }
    }
  }
}
```

**Comment by Yehonal** [comment]
i'm working on it using "sequelizeConnection" from graphql-sequelize

**Comment by Yehonal** [comment]
fixed on PR
