### ISSUE TITLE
Option scopes is not documented in readme

### ISSUE THREAD

**Issue by Yehonal** [alirizwan/sequelize-graphql-schema#8]
https://github.com/alirizwan/sequelize-graphql-schema/blob/develop/src/sequelize-graphql-schema.js#L47

in code we've scopes option that is passed to model on resolver, but what exactly does?

we should document it

**Comment by alirizwan** [comment]
they apply sequelize scopes on queries: http://docs.sequelizejs.com/manual/tutorial/scopes.html

**Comment by alirizwan** [comment]
I will extend documentation over the weekend.
